# Generated by Django 4.0.5 on 2022-08-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_pub_date_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
