# Generated by Django 4.0.5 on 2022-08-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
