# Generated by Django 4.0.5 on 2022-08-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0039_remove_student_student_id'),
        ('forum', '0006_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_netid',
        ),
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.CASCADE, to='simple_judge.student'),
            preserve_default=False,
        ),
    ]
