# Generated by Django 4.0.5 on 2022-08-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_remove_post_author_name_remove_post_author_netid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='student',
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author_netid',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
