# Generated by Django 4.0.5 on 2022-08-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_remove_post_student_post_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.IntegerField(default=-1),
        ),
    ]
