# Generated by Django 4.0.5 on 2022-07-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0002_remove_student_department_student_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
