# Generated by Django 4.0.5 on 2022-07-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0003_student_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ifpassed',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
