# Generated by Django 4.0.5 on 2022-07-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0004_question_ifpassed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ifpassed',
            field=models.BooleanField(verbose_name='ifpassed'),
        ),
    ]
