# Generated by Django 4.0.5 on 2022-07-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0005_alter_question_ifpassed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.JSONField(verbose_name='quiz_content'),
        ),
    ]
