# Generated by Django 4.0.5 on 2022-07-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0006_alter_question_question_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.JSONField(null=True),
        ),
    ]
