# Generated by Django 4.0.5 on 2022-07-02 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0007_alter_question_question_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_content',
        ),
    ]
