# Generated by Django 4.0.5 on 2022-07-04 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0009_question_question_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questiondict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question_content', models.JSONField(verbose_name='quiz_content')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_content',
        ),
    ]
