# Generated by Django 4.0.5 on 2022-07-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0010_questiondict_remove_question_question_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondict',
            name='question_type',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
