# Generated by Django 4.0.5 on 2022-07-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0012_questiondict_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
