# Generated by Django 4.0.5 on 2022-07-05 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0013_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 11, 49, 21, 743854, tzinfo=utc), verbose_name='date published'),
        ),
    ]
