# Generated by Django 4.0.5 on 2022-07-05 12:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0020_questiondict_question_level_alter_question_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiondict',
            name='question_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 12, 16, 35, 774547, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 12, 16, 35, 774526, tzinfo=utc), verbose_name='date published'),
        ),
    ]
