# Generated by Django 4.0.5 on 2022-07-06 05:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0021_questiondict_question_week_alter_question_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 5, 52, 41, 769553, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 5, 52, 41, 769531, tzinfo=utc), verbose_name='date published'),
        ),
    ]
