# Generated by Django 4.0.5 on 2022-07-12 05:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0023_alter_question_due_date_alter_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='submission_times',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 5, 35, 49, 211563, tzinfo=utc), verbose_name='date due'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 12, 5, 35, 49, 211539, tzinfo=utc), verbose_name='date published'),
        ),
    ]
