# Generated by Django 4.0.5 on 2022-07-26 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0024_alter_question_due_date_alter_question_pub_date'),
        ('simple_judge', '0024_question_submission_times_alter_question_due_date_and_more'),
    ]

    operations = [
    ]
