# Generated by Django 4.0.5 on 2022-07-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0028_question_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ifpassed',
            field=models.BooleanField(default=False, verbose_name='ifpassed'),
        ),
    ]
