# Generated by Django 4.0.5 on 2022-07-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0029_alter_question_ifpassed'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='question_due_dict',
            field=models.JSONField(default={'week1': ['2022-7-29 6:00', '2022-7-29 23:59']}),
        ),
    ]
