# Generated by Django 4.0.5 on 2022-07-29 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0030_student_question_due_dict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
