# Generated by Django 4.0.5 on 2022-07-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0031_remove_question_due_date_remove_question_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_netid',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=20),
        ),
    ]
