# Generated by Django 4.0.5 on 2022-07-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0032_student_student_netid_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_netid',
            field=models.CharField(max_length=8),
        ),
    ]
