# Generated by Django 4.0.5 on 2022-08-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0035_alter_student_offline_time_alter_student_online_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
