# Generated by Django 4.0.5 on 2022-08-03 08:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0036_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='offline_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 6, 30, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='online_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 6, 0, tzinfo=utc)),
        ),
    ]
