# Generated by Django 4.0.5 on 2022-08-03 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0037_alter_student_offline_time_alter_student_online_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='offline_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 6, 30)),
        ),
        migrations.AlterField(
            model_name='student',
            name='online_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 6, 0)),
        ),
    ]
