# Generated by Django 4.0.5 on 2022-08-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0038_alter_student_offline_time_alter_student_online_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
