# Generated by Django 4.0.5 on 2022-11-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0040_auto_20220919_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='logx_json',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='logx',
            field=models.TextField(blank=True),
        ),
    ]
