# Generated by Django 4.0.5 on 2022-11-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0041_question_logx_json_alter_question_logx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='logx_json',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
