# Generated by Django 4.0.5 on 2022-11-11 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_judge', '0042_alter_question_logx_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='logx_json',
        ),
    ]
